[supervisord]
nodaemon=true

[program:mt5_cluster]
command=/bin/bash /root/start_cluster.sh
autorestart=true
environment=WINEPREFIX="/config/.wine",HOME="/root"
stdout_logfile=/var/log/mt5_cluster.log
stderr_logfile=/var/log/mt5_cluster.err
